name: Bug
description: Report something broken.
title: ""
labels: ["type:bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Sparse attention mask allows attending to future tokens."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
